#!/bin/bash

revno=`bzr revno`
revnoplus=`expr $revno + 1`

# search and replace version strings
echo "version bump to v$revnoplus"

for f in index.html 0_START.pd
do
	perl -pe "s{v\d+}{v$revnoplus}g" < $f > new-$f
	mv new-$f $f
done

echo "committing.."
bzr commit -m 'version bump'

echo "bzr exporting"
bzr export GarageAcidLab-v$revnoplus.zip

echo "rsyncing..."
rsync -avz . mccormick.cx:~/mccormick.cx/projects/GarageAcidLab/
